# Generated by Django 4.1.2 on 2022-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_helper', '0002_task_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
