# Generated by Django 4.1.2 on 2022-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_helper', '0004_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
